name: status-check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: status-check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: run test
        run: |
          go install golang.org/x/lint/golint
          golint ./...
          go test ./...

      - name: run build
        run: go build -v .
